language: java
jdk: oraclejdk8
before_install:
- git clone git@github.com:ThilinaManamgoda/Mongodb-Jongo-JAVA.git
- pushd Mongodb-Jongo-JAVA && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V && popd
script: 
- mvn test -B
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn cobertura:cobertura
after_success:
- bash <(curl -s https://codecov.io/bash)