language: java
jdk: oraclejdk8
before_install:
- wget https://github.com/ThilinaManamgoda/Mongodb-Jongo-JAVA/archive/master.zip
- unzip master.zip -d .
- pushd Mongodb-Jongo-JAVA-master && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V && popd
script: 
- mvn test -B
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn cobertura:cobertura
after_success:
- bash <(curl -s https://codecov.io/bash)